name: Filter test

on:
  workflow_dispatch:

jobs:
  master-job:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check-commit-message.outputs.result }}
    steps:
      - name: Check commit message
        id: check-commit-message
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; 
          then
            echo "::set-output name=result::true"
          else
            echo "::set-output name=result::false"
          fi

  slave-job:
    needs: master-job
    if: ${{ needs.master-job.outputs.result == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "slave-job"
